#define QCM_Q KC_Q
#define QCM_W KC_W
#define QCM_E KC_F
#define QCM_R KC_P
#define QCM_T KC_G
#define QCM_Y KC_J
#define QCM_U KC_L
#define QCM_I KC_U
#define QCM_O KC_Y
#define QCM_P KC_SCLN
#define QCM_A KC_A
#define QCM_S KC_R
#define QCM_D KC_S
#define QCM_F KC_T
#define QCM_G KC_D
#define QCM_H KC_H
#define QCM_J KC_N
#define QCM_K KC_E
#define QCM_L KC_I
#define QCM_SCLN KC_O
#define QCM_QUOT KC_QUOT
#define QCM_Z KC_Z
#define QCM_X KC_X
#define QCM_C KC_C
#define QCM_V KC_V
#define QCM_B KC_B
#define QCM_N KC_K
#define QCM_M KC_M
#define QCM_COMM KC_COMM
#define QCM_DOT KC_DOT
#define QCM_SLSH KC_SLSH
